# Generated by Django 6.0.7 on 2026-07-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
                ('ano_fundacao', models.IntegerField()),
                ('qtde_membros', models.IntegerField()),
                ('pontuacao', models.IntegerField(default=0)),
            ],
        ),
    ]
